version: "3"
services:
    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongodb-data:/data/db

    backend:
        image: my-backend-image:${BUILD_NUMBER}
        ports:
            - "3001:3001"
        depends_on:
            - mongodb

    frontend:
        image: my-frontend-image:${BUILD_NUMBER}

        ports:
            - "5173:5173"
        depends_on:
            - backend
        environment:
            - REACT_APP_BACKEND_URL=http://backend:3001

volumes:
    mongodb-data:
